module.exports = {
    apps: [
        {
            name: 'hostbol-reverb',
            script: 'artisan',
            interpreter: 'php',
            args: 'reverb:start --host=0.0.0.0 --port=3015',
            cwd: __dirname,
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            max_restarts: 10,
            exp_backoff_restart_delay: 100,
            kill_timeout: 10000,
            error_file: './storage/logs/pm2/reverb-error.log',
            out_file: './storage/logs/pm2/reverb-out.log',
            merge_logs: true,
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'hostbol-queue',
            script: 'artisan',
            interpreter: 'php',
            args: 'queue:work --tries=3 --timeout=60',
            cwd: __dirname,
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            max_restarts: 10,
            exp_backoff_restart_delay: 100,
            kill_timeout: 10000,
            error_file: './storage/logs/pm2/queue-error.log',
            out_file: './storage/logs/pm2/queue-out.log',
            merge_logs: true,
        },
    ],
};